# use_frameworks!

platform :ios, '9.0'

target 'NestedTableView_Example' do
  pod 'NestedTableView', :path => '../'
  # pod 'NestedTableView', :git => 'git@github.com:CrystalBlack/NestedTableView.git'
  pod 'Masonry'
  target 'NestedTableView_Tests' do
    inherit! :search_paths

    
  end
end
